[MeterBar0]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed0]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar1]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed1]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar2]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed2]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar3]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed3]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar4]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed4]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar5]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed5]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar6]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed6]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar7]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed7]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar8]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed8]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar9]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed9]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar10]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed10]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar11]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed11]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar12]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed12]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar13]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed13]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar14]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed14]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar15]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed15]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar16]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed16]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar17]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed17]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar18]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed18]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar19]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed19]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar20]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed20]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar21]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed21]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar22]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed22]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar23]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed23]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar24]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed24]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar25]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed25]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar26]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed26]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar27]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed27]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar28]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed28]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar29]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed29]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar30]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed30]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar31]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed31]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar32]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed32]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar33]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed33]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar34]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed34]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar35]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed35]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar36]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed36]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar37]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed37]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar38]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed38]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar39]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed39]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar40]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=43
Shape=Rectangle 0,0,(23*0.05),(-(43-(23*0.05))*[MeasureAudioSmoothed40]-(23*0.05)),((23*0.05)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1